### ISSUE TITLE
Add `kotlin-multiplatform-mobile` topic

### ISSUE THREAD

**Issue by danil-pavlov** [Oztechan/CCC#1297]
The Kotlin team is now changing its approach to the Multiplatform mobile samples. The number of great projects is growing, and we can't keep adding them to the already huge table in the documentation.

Instead, we decided to keep a handful of projects in the table and give a link to a handy search by the GitHub topic. To [add the topic to your project](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics#adding-topics-to-your-repository), please use the `kotlin-multiplatform-mobile` tag in the **About** section of your GitHub repository.

**Comment by mustafaozhan** [comment]
Hello @danil-pavlov thank you for creating this issue, just added the label!
