### ISSUE TITLE
From where can I get apis?

### ISSUE THREAD

**Issue by egbamddeveloper** [Oztechan/CCC#2071]
## Description
Hi, about internal object BuildKonfig 

  public const val BASE_URL_BACKEND: String = "https://api.exchangerate.host"
  public const val BASE_URL_API: String = "http://www.private-url.com"
  public const val BASE_URL_API_PREMIUM: String =  "http://www.private-url.com"
  public const val API_KEY_PREMIUM: String = "http://www.private-url.com"

From where can I get apis?
Thanks :)

**Comment by mustafaozhan** [comment]
Hello, these are production values and can not be provided to others for security reasons...

In the future we are planing to add testing endpoints but as for today they are all private
