### ISSUE TITLE
Copy currency conversion result in to the clipboard

### ISSUE THREAD

**Issue by franco27** [Oztechan/CCC#555]
Hello
 I just tried your application and I find it a pity that there is no possibility to copy the result of the currency conversion to the clipboard.

 Maybe you planned an option to set the number of decimal places.

Thanks

**Comment by mustafaozhan** [comment]
Hello @franco27 👋 

Thanks a lot for reporting this, we will be adding it in our next release 🚀

**Comment by franco27** [comment]
Thanks 😊

**Comment by franco27** [comment]
Hello .
normally you have implemented the possibility to copy the result of the currency conversion.
I have installed the update.  But how to do it?
I made a long click on the result or move left or right on the result, but nothing happens...

**Comment by franco27** [comment]
Thank you for answering me. 
Yes I am fine with the version 258.
But when I do a long click on the result nothing happens.

**Comment by mustafaozhan** [comment]
Hello @franco27 👋 

Thank you for feedback I just check with the latest version and it works in my 3 devices.

Just to be sure, if we take an example of this picture
https://raw.githubusercontent.com/CurrencyConverterCalculator/CCC/master/art/android/1.png

You should be long pressing on ie. `1 142.95 $` text, So the conversions in the List.

Is it not working for you ?

**Comment by franco27** [comment]
I had uninstalled it. I reinstalled it and now I have the copy notification.
It is solved. Thanks

Before uninstalling, I had followed your instructions. Well, now it works.

**Comment by mustafaozhan** [comment]
That's great news! 🎉 Thank you for the confirmation 🙂

**Comment by franco27** [comment]
It doesn't work anymore. your copy system is rather capricious. it doesn't work anymore

**Comment by mustafaozhan** [comment]
Hello, basically nothing changed in app between your trials. I think you are having problem on long click

> the result moves in the bar

This will only happen when you `click` an item

While when you `long click` on output of an item, it should copy to clipboard
and when you `long click` on the currency flag or code of an item, it should show conversion.

**Comment by franco27** [comment]
yes, indeed I understood my mistake. I made a long click a little next to the element to copy on the same line.
On the other hand, I do not succeed from the clipboard, to paste a number (or a digit) or sum, in your calculator to obtain the monetary conversion.
